### ISSUE TITLE
Couldn't Generate Local Execution Plan

### ISSUE THREAD

**Issue by uniuuu** [Harshetjain666/terraform-aws-eks-fargate-cluster#1]
→ Plan
  ✘ Couldn't Generate Local Execution Plan

Error: Unsupported attribute

  on output.tf line 17, in output "server_dns":
  17:     value = "${data.kubernetes_ingress.address.load_balancer_ingress}"

This object has no argument, nested block, or exported attribute named
"load_balancer_ingress".

Error: Unsupported argument

  on kubernetes/main.tf line 16, in provider "kubernetes":
  16:   load_config_file       = false

An argument named "load_config_file" is not expected here.

**Comment by Harshetjain666** [comment]
Solved please check again now.
